### ISSUE TITLE
train.py 训练时环境变量不合理，RANK_ID不应该被感知

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#101]
whl版本：mindocr/version/202303/20230320
源码：2023/3/25 main分支
复现：python tools/train.py -c configs/det/db_r50_icdar15.yaml > case.log 2>&1
报错信息：
Traceback (most recent call last):
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 178, in <module>
    main(config)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 44, in main
    init()
  File "/root/archiconda3/envs/mindocr_test/lib/python3.9/site-packages/mindspore/communication/management.py", line 145, in init
    _check_parallel_envs()
  File "/root/archiconda3/envs/mindocr_test/lib/python3.9/site-packages/mindspore/communication/management.py", line 68, in _check_parallel_envs
    raise RuntimeError("Environment variables RANK_ID has not been exported, please export variables 'RANK_ID'.")
RuntimeError: Environment variables RANK_ID has not been exported, please export variables 'RANK_ID'.

**Comment by HaoyangLee** [comment]
相关PR https://github.com/mindspore-lab/mindocr/pull/164
文档已说明模型各种运行模式下的参数配置情况。

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
