### ISSUE TITLE
db_r50_icdar15.yaml 单卡eval 当pretrained: True 时 报错，eval应该和 pretrained无关，需要解耦

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#130]
关联位置：https://github.com/mindspore-lab/mindocr/blob/main/configs/det/dbnet/db_r50_icdar15.yaml
源码：2023/3/29 main分支
mindcv whl版本：2023/3/29 源码安装
Describe the expected behavior / 预期结果 (Mandatory / 必填)
db_r50_icdar15.yaml 单卡eval 当pretrained: True 时 正常
复现命令示例：python /data3/cty/mind_lab/test_mindocr/mindocr/tools/eval.py -c /data3/cty/mind_lab/test_mindocr/mindocr_models_test_data/db_r50_icdar15/test_eval_db_r50_icdar15_ascend_icdar15_1p_graph_001/db_ricdar15.yaml > case.log 2>&1
具体问题：eval 会被 pretrained: True影响  必须 pretrained: False才能正常eval，这应该不合理，eval应该和 pretrained无关，需要解耦吧？当pretrained: True 时eval具体报错如下：
==> Dataset output columns:
         ['image', 'polys', 'ignore_tags']
Traceback (most recent call last):
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/eval.py", line 98, in <module>
    main(config)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/eval.py", line 47, in main
    network = build_model(cfg.model, ckpt_load_path=cfg.eval.ckpt_load_path)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/models/builder.py", line 53, in build_model
    network = BaseModel(config)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/models/base_model.py", line 19, in __init__
    self.backbone = build_backbone(backbone_name, **config.backbone)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/models/backbones/builder.py", line 40, in build_backbone
    backbone = create_fn(**kwargs)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/models/backbones/det_resnet.py", line 51, in det_resnet50
    load_pretrained(model, default_cfg)
  File "/root/archiconda3/envs/mindocr_test/lib/python3.9/site-packages/mindcv/models/utils.py", line 38, in load_pretrained
    param_dict = load_checkpoint(os.path.join(download_path, os.path.basename(default_cfg["url"])))
  File "/root/archiconda3/envs/mindocr_test/lib/python3.9/site-packages/mindspore/train/serialization.py", line 554, in load_checkpoint
    raise ValueError(f"The loaded parameter dict is empty after filter or specify, please check whether "
ValueError: The loaded parameter dict is empty after filter or specify, please check whether 'filter_prefix' or 'specify_prefix' are set correctly.

**Comment by HaoyangLee** [comment]
PR #131

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
