### ISSUE TITLE
FceNet评估报错：IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by HustleOoo** [mindspore-lab/mindocr#544]
运行python tools/eval.py --config configs/det/fcenet/fce_icdar15.yaml时，发生报错如下：

Traceback (most recent call last):
  File "tools/eval.py", line 145, in <module>
    main(config)
  File "tools/eval.py", line 135, in main
    measures = net_evaluator.eval()
  File "/home/mindocr-main/mindocr/utils/evaluator.py", line 153, in eval
    preds = self.postprocessor(preds, **data_info)
  File "/home/mindocr-main/mindocr/postprocess/det_base_postprocess.py", line 109, in __call__
    result = self.rescale(result, shape_list)
  File "/home/mindocr-main/mindocr/postprocess/det_base_postprocess.py", line 152, in rescale
    result[field][i] = self._rescale_polygons(sample, shape_list[i])
IndexError: index 1 is out of bounds for axis 0 with size 1

查看源码发现shape_list列表中只有一个元素，进行到第二个循环i=1时，发生越界，请问下这种情况如何解决？

**Comment by panshaowu** [comment]
@HustleOoo 
您好，感谢您的反馈。该问题已经在PR #584 中修复。
该问题是`shape_list`和`result['polys']`的元素数量不一致引发的，已通过调整后处理结果中数据结构解决。
测试工程师已经在MindSpore r2.2.11上复验，可正常运行`python tools/eval.py --config configs/det/fcenet/fce_icdar15.yaml`脚本，请尝试拉取最新代码和运行。
