### ISSUE TITLE
MindOCR推理export.py时--model_name_or_config configs/det/dbnet/db++_r50_icdar15.yaml失败

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#630]
MindOCR推理export.py时 --model_name_or_config dbnetpp_resnet50成功，--model_name_or_config configs/det/dbnet/db++_r50_icdar15.yaml失败。原因是db++_r50_icdar15.yaml中的字段++校验出错。
具体报错信息如下：
[2023-11-30 18:51:59] mindocr.models.utils.load_model INFO - Finish loading model checkoint from /nfs_for_sync/Mindlab_data/dataset/mindocr_infer_ckpt/dbnetpp_resnet50-068166c2.ckpt. If no parameter fail-load warning displayed, all checkpoint params have been successfully loaded.
[2023-11-30 18:51:59] mindocr.export INFO - Set the AMP level of the model to be `O0`.
Traceback (most recent call last):
  File "/data1/jenkins/workspace/source_code/mindocr//tools/export.py", line 171, in <module>
    export(**vars(args))
  File "/data1/jenkins/workspace/source_code/mindocr//tools/export.py", line 88, in export
    ms.export(net, x, file_name=output_path, file_format="MINDIR")
  File "/usr/local/lib/python3.7/site-packages/mindspore/train/serialization.py", line 1575, in export
    Validator.check_file_name_by_regular(file_name)
  File "/usr/local/lib/python3.7/site-packages/mindspore/_checkparam.py", line 586, in check_file_name_by_regular
    raise ValueError(f"{prim_name} '{target}' is illegal, it must be match regular '{reg}'.")
ValueError: The 'db++_r50_icdar15.mindir' is illegal, it must be match regular '^[0-9a-zA-Z@\_\-\.\:\/\\]+$'.

**Comment by panshaowu** [comment]
感谢您的反馈。该问题已在PR#664中修复，可通过拉取最新的代码获取。
