### ISSUE TITLE
将ch_PP-OCRv4转换成mindir格式后推理报错

### ISSUE THREAD

**Issue by gongjimin** [mindspore-lab/mindocr#756]
## 本机环境

1. 操作系统：UOS Server 20 1060e
2. CPU/MEM：Kunpeng-920 96core / 128GB
3. NPU硬件规格：Ascend 300I Pro 24GB*2 （芯片为310P3）
4. NPU驱动版本：23.0.1
5. 容器镜像：基于ubuntu20.04自制
6. 容器内CANN版本：7.0.1
7. mindspore和mindspore_lite版本：2.2.10
8. mindocr版本：0.3.2（从源码安装，但源码0.3.2的tag中version显示为4.0.0）

## 重现步骤

1. 在此环境下执行```bash paddle2mindir.sh -m=ch_PP-OCRv4 -p=./```完成ch_PP-OCRv4模型下载和转换（转换过程中CPU持续100%大约30分钟）
2. 下载字典文件```ppocr_keys_v1.txt```
3. 使用检测和识别模型使用执行推理：
    ```bash
    python3 /Work/mindocr/deploy/py_infer/infer.py \
        --backend=lite \
        --input_images_dir=/Work/pic \
        --det_model_path=/Work/mindocr/tools/ch_PP-OCRv4_det_db_dynamic_output.mindir \
        --det_model_name_or_config=ch_pp_rec_OCRv4 \
        --rec_model_path=/Work/mindocr/tools/ch_PP-OCRv4_rec_crnn_dynamic_output.mindir \
        --rec_model_name_or_config=ch_pp_rec_OCRv4 \
        --character_dict_path=/Work/mindocr/tools/ppocr_keys_v1.txt \
        --res_save_dir=/Work/ch_rec_infer_results
    ```

错误信息为：

```txt
[ERROR] MINDOCR(232186:281457484137952,Process-1:26):2024-10-28-10:16:14.801.875 [src/parallel/framework/module_base.py:40] DetPostNode init failed: __init__() got an unexpected keyword argument 'rescale_fields'
Process Process-1:26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Work/mindocr/deploy/py_infer/src/parallel/framework/module_base.py", line 41, in process_handler
    raise error
  File "/Work/mindocr/deploy/py_infer/src/parallel/framework/module_base.py", line 36, in process_handler
    params = self.init_self_args()
  File "/Work/mindocr/deploy/py_infer/src/parallel/module/detection/det_post_node.py", line 16, in init_self_args
    self.text_detector.init(preprocess=False, model=False, postprocess=True)
  File "/Work/mindocr/deploy/py_infer/src/infer/infer_base.py", line 52, in init
    self._init_postprocess()
  File "/Work/mindocr/deploy/py_infer/src/infer/infer_det.py", line 57, in _init_postprocess
    self.postprocess_ops = build_postprocess(self.args.det_config_path, rescale_fields=["polys"])
  File "/Work/mindocr/deploy/py_infer/src/data_process/postprocess/builder.py", line 86, in build_postprocess
    processor = Postprocessor(tasks, **kwargs)
  File "/Work/mindocr/deploy/py_infer/src/data_process/postprocess/builder.py", line 24, in __init__
    self._ops_func = ops(**params)
TypeError: __init__() got an unexpected keyword argument 'rescale_fields'
[WARNING] ME(232233,fffbed5c85e0,python3):2024-10-28-10:16:21.288.938 [mindspore/lite/src/extendrt/kernel/ascend/src/custom_ascend_kernel.cc:171] Resize] Invalid inputs or output shapes.
[WARNING] ME(232161,fffbed5c85e0,python3):2024-10-28-10:16:21.872.553 [mindspore/lite/src/extendrt/kernel/ascend/src/custom_ascend_kernel.cc:171] Resize] Invalid inputs or output shapes.
```

错误信息出现后，命令行卡住需要按```Ctrl+C```才能退出。

**Comment by alien-0119** [comment]
您好，`TypeError: __init__() got an unexpected keyword argument 'rescale_fields'`此错误是由于--det_model_name_or_config参数指定了文本识别(rec)模型的config而导致的：`--det_model_name_or_config=ch_pp_**rec**_OCRv4 \`。
这里建议您使用`--det_model_name_or_config=/Work/mindocr/deploy/py_infer/src/configs/det/ppocr/ch_PP-OCRv4_det_cml.yaml`及`--rec_model_name_or_config=/Work/mindocr/deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv4_rec_distillation.yaml`来替换您原本命令的这两个入参。

另外，模型转换过程中，`paddle2mindir.sh`会调用`converter_lite`。`converter_lite`在这个过程中会占用很多CPU，希望这点对您有所帮助。

**Comment by gongjimin** [comment]
> 您好，`TypeError: __init__() got an unexpected keyword argument 'rescale_fields'`此错误是由于--det_model_name_or_config参数指定了文本识别(rec)模型的config而导致的：`--det_model_name_or_config=ch_pp_**rec**_OCRv4 \`。 这里建议您使用`--det_model_name_or_config=/Work/mindocr/deploy/py_infer/src/configs/det/ppocr/ch_PP-OCRv4_det_cml.yaml`及`--rec_model_name_or_config=/Work/mindocr/deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv4_rec_distillation.yaml`来替换您原本命令的这两个入参。
> 
> 另外，模型转换过程中，`paddle2mindir.sh`会调用`converter_lite`。`converter_lite`在这个过程中会占用很多CPU，希望这点对您有所帮助。

万分感谢，现在已经可以成功加载ppocrv4的文本检测和识别模型了。
